version: '3.8'

services:
  db:
    image: mariadb
    hostname: mariadb-${GIBBON_SITENAME}
    restart: always
    environment:
      - LANG
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - gibbon-db-data:/var/lib/mysql
      - gibbon-db-log:/var/log/mysql
      - ./db/backup:/backup
      - ./db/backupscripts:/backupscripts
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ${GIBBON_NETWORK}

  apache:
    build: ./webserver
    hostname: apache-${GIBBON_SITENAME}
    restart: always
    depends_on:
      - php
    environment:
      - GIBBON_SITENAME
      - SERVER_ADMIN_MAIL
      - VIRTUAL_HOST=${GIBBON_SITENAME}
#      - LETSENCRYPT_HOST
#      - LETSENCRYPT_EMAIL
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gibbon-root:${GIBBON_BASEDIR}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${GIBBON_SITE_NAME}.rule=Host(`${GIBBON_SITEURL}`, `${GIBBON_WWW_URL}`)
      - traefik.http.routers.${GIBBON_SITE_NAME}.entrypoints=web
      - traefik.http.routers.${GIBBON_SITE_NAME}.middlewares=redirect-to-https@docker
      - "traefik.http.routers.${GIBBON_SITE_NAME}.entrypoints=http"
      - "traefik.http.middlewares.${GIBBON_SITE_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${GIBBON_SITE_NAME}.middlewares=${GIBBON_SITE_NAME}-https-redirect"
      - "traefik.http.routers.${GIBBON_SITE_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${GIBBON_SITE_NAME}-secure.rule=Host(`${GIBBON_SITEURL}`)"
      - "traefik.http.routers.${GIBBON_SITE_NAME}-secure.tls=true"
      - "traefik.http.routers.${GIBBON_SITE_NAME}-secure.service=${GIBBON_SITE_NAME}"
      - "traefik.http.services.${GIBBON_SITE_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - ${GIBBON_NETWORK}

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      target: dev
    hostname: php-${GIBBON_SITENAME}
    restart: always
    environment:
      - GIBBON_SITENAME
      - GIBBON_VERSION
#      - GIBBON_DB_HOST=mariadb
#      - GIBBON_DB_PORT=3306
#      - GIBBON_DB_DB=${MYSQL_DATABASE}
#      - GIBBON_DB_USER=${MYSQL_USER}
#      - GIBBON_DB_PASSWORD=${MYSQL_PASSWORD}
      - GIBBON_BASEDIR
    volumes:
      - gibbon-root:${GIBBON_BASEDIR}
    networks:
      - ${GIBBON_NETWORK}

  crontab:
    image: willfarrell/crontab
    depends_on:
      - php
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ./crontab/config.json
        target: /opt/crontab/config.json
        read_only: true

  smtpd:
    image: namshi/smtp
    restart: always
    depends_on:
      - php
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MAILNAME
      - SMARTHOST_ADDRESS
      - SMARTHOST_PORT
      - SMARTHOST_USER
      - SMARTHOST_PASSWORD
      - SMARTHOST_ALIASES
    networks:
      - ${GIBBON_NETWORK}

volumes:
  gibbon-db-data:
  gibbon-db-log:
  gibbon-root:

  proxy:
    external:
      name: proxy
  gibbon##sitename_network:
    external:
      name: [###Network Placeholder###]