version: '3.8'

services:
  db:
    image: mariadb
    hostname: mariadb-${GIBBON_SITENAME}
    restart: always
    environment:
      - LANG
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - gibbon-db-data:/var/lib/mysql
      - gibbon-db-log:/var/log/mysql
      - ./db/backup:/backup
      - ./db/backupscripts:/backupscripts
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ${GIBBON_SITENAME}

  apache:
    build: ./webserver
    hostname: apache-${GIBBON_SITENAME}
    restart: always
    depends_on:
      - php
    environment:
      - GIBBON_SITENAME
      - SERVER_ADMIN_MAIL
      - VIRTUAL_HOST=${GIBBON_SITENAME}
    #      - LETSENCRYPT_HOST
    #      - LETSENCRYPT_EMAIL
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gibbon-root:${GIBBON_BASEDIR}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${GIBBON_SITENAME}.rule=Host(`${GIBBON_SITEURL}`, `${GIBBON_WWW_URL}`)"
      - "traefik.http.routers.${GIBBON_SITENAME}.entrypoints=web"
      - "traefik.http.routers.${GIBBON_SITENAME}.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.${GIBBON_SITENAME}.entrypoints=http"
      - "traefik.http.middlewares.${GIBBON_SITENAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${GIBBON_SITENAME}.middlewares=${GIBBON_SITENAME}-https-redirect"
      - "traefik.http.routers.${GIBBON_SITENAME}-secure.entrypoints=https"
      - "traefik.http.routers.${GIBBON_SITENAME}-secure.rule=Host(`${GIBBON_SITEURL}`)"
      - "traefik.http.routers.${GIBBON_SITENAME}-secure.tls=true"
      - "traefik.http.routers.${GIBBON_SITENAME}-secure.service=${GIBBON_SITENAME}"
      - "traefik.http.services.${GIBBON_SITENAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - ${GIBBON_SITENAME}

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      target: dev
    hostname: php-${GIBBON_SITENAME}
    restart: always
    environment:
      - GIBBON_SITENAME
      - GIBBON_VERSION
      #      - GIBBON_DB_HOST=mariadb
      #      - GIBBON_DB_PORT=3306
      #      - GIBBON_DB_DB=${MYSQL_DATABASE}
      #      - GIBBON_DB_USER=${MYSQL_USER}
      #      - GIBBON_DB_PASSWORD=${MYSQL_PASSWORD}
      - GIBBON_BASEDIR
    volumes:
      - gibbon-root:${GIBBON_BASEDIR}
    networks:
      - ${GIBBON_SITENAME}

  crontab:
    image: willfarrell/crontab
    depends_on:
      - php
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ./crontab/config.json
        target: /opt/crontab/config.json
        read_only: true

  smtpd:
    image: namshi/smtp
    restart: always
    depends_on:
      - php
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MAILNAME
      - SMARTHOST_ADDRESS
      - SMARTHOST_PORT
      - SMARTHOST_USER
      - SMARTHOST_PASSWORD
      - SMARTHOST_ALIASES
    networks:
      - ${GIBBON_SITENAME}

volumes:
  gibbon-db-data:
  gibbon-db-log:
  gibbon-root:


networks:
  proxy:
    external:
      name: proxy

  gibbon:
    external:
      name: gibbon
  # The containers above use a custom private network '${GIBBON_SITENAME}'.
  # The variable GIBBON_SITENAME is defined in the .env file.
  # 1. Update the .env file as per your preferences (please choose secure passwords and usernames)
  # 2. If you named GIBBON_SITENAME as 'mygibbon', then create a new network using the following example (where 'mygibbon is replaced by the name that you chose):
  #    docker network create mygibbon
  # 2. Replace the text 'gibbon' in the line below, and the last line below with the network name that you chose, e.g. mygibbon
